mex -outdir bin ...
      CFLAGS="\$CFLAGS -std=c99 -O3 -fPIC" -largeArrayDims ...
      external/liblinear-1.96/matlab/train.c ...
      external/liblinear-1.96/matlab/linear_model_matlab.c ...
      external/liblinear-1.96/linear.cpp ...
      external/liblinear-1.96/tron.cpp ...
      "external/liblinear-1.96/blas/*.c" ...
      -output liblinear_train;
mex -outdir bin ...
      CFLAGS="\$CFLAGS -std=c99 -O3 -fPIC" -largeArrayDims ...
      external/liblinear-1.96/matlab/predict.c ...
      external/liblinear-1.96/matlab/linear_model_matlab.c ...
      external/liblinear-1.96/linear.cpp ...
      external/liblinear-1.96/tron.cpp ...
      "external/liblinear-1.96/blas/*.c" ...
      -output liblinear_predict;
